// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xktkvrctjsonrscocuvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrdGt2cmN0anNvbnJzY29jdXZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMDU5NTIsImV4cCI6MjA4OTY4MTk1Mn0.wrcTS5OO8rOWOO6k8DMg2WtPyoYweWLPMygtJnhLfsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
